import logging
import re

logger = logging.getLogger(__name__)

# Maximum response length for Signal delivery.  Anything longer gets truncated
# with a note.  Signal itself can handle ~4000 chars but users read on phones
# — long walls of text are useless.
_MAX_RESPONSE_LENGTH = 1400

# Internal metadata markers that must NEVER reach the user.
# These are generated by internal QA processes (critic, self-report, proactive
# triggers) and should be stripped before delivery.
_INTERNAL_METADATA_PATTERNS = [
    re.compile(r"\n+---\n+\*?\*?\[Critic Review\]\*?\*?\n.*", re.DOTALL | re.IGNORECASE),
    re.compile(r"\n+---\n+\*?\*?\[Proactive Notes?\]\*?\*?\n.*", re.DOTALL | re.IGNORECASE),
    re.compile(r"\n+---\n+\*?\*?\[Self[- ]Report\]\*?\*?\n.*", re.DOTALL | re.IGNORECASE),
    re.compile(r"\n+---\n+\*?\*?\[Debug\]\*?\*?\n.*", re.DOTALL | re.IGNORECASE),
    re.compile(r"\n+---\n+\*?\*?\[Sub-agent.*?\]\*?\*?\n.*", re.DOTALL | re.IGNORECASE),
    re.compile(r"\n+Note: \d+ sub-tasks? failed\.?\s*$", re.DOTALL | re.IGNORECASE),
    # Vetting reviewer editorial footnotes (⚠️ / ⚠ / *Note:* italic disclaimers)
    re.compile(r"\n+\s*⚠️?\s*\n?\s*\*.*?\*\s*$", re.DOTALL),
    # Catch reviewer meta-commentary about "original model data", "values above", etc.
    re.compile(r"\n+\s*⚠️?\s*.*?(?:original model|values above|confirm with your|data contained).*$", re.DOTALL | re.IGNORECASE),
    # Generic reviewer disclaimer pattern: italic block at the end starting with *
    re.compile(r"\n+\s*\*(?:Note|Disclaimer|Warning|Caveat|Editor|Reviewer)[:\s].*?\*\s*$", re.DOTALL | re.IGNORECASE),
]


def _strip_internal_metadata(text: str) -> str:
    """Strip internal QA artefacts from response text.

    Removes critic reviews, proactive notes, self-reports, debug info,
    and sub-agent failure notes. These should never reach the user.
    """
    if not text:
        return text
    for pattern in _INTERNAL_METADATA_PATTERNS:
        text = pattern.sub("", text)
    return text.strip()


def truncate_for_signal(text: str, max_length: int = _MAX_RESPONSE_LENGTH) -> str:
    """Truncate text at a sentence boundary for Signal delivery.

    Returns the truncated text with a note if truncation occurred.
    """
    if not text or len(text) <= max_length:
        return text

    truncated = text[:max_length]
    # Try to cut at last sentence end
    last_period = truncated.rfind(". ")
    last_newline = truncated.rfind("\n")
    cut_at = max(last_period, last_newline)
    if cut_at > max_length // 2:
        truncated = truncated[:cut_at + 1]
    return truncated.rstrip() + "\n\n[Full response attached as document]"


def _clean_response(text: str) -> str:
    """Strip internal metadata and enforce length limit for Signal delivery.

    Users should only see the final answer — never internal QA artefacts,
    sub-agent debug info, or proactive scan results.
    """
    text = _strip_internal_metadata(text)
    return truncate_for_signal(text)


# ── L6: Epistemic Humility — Escalation Triggers ─────────────────────────────

# Phrases that indicate the agent itself is expressing uncertainty
_UNCERTAINTY_PHRASES = [
    "i'm not sure", "i am not sure", "i cannot verify",
    "i'm unable to confirm", "conflicting information",
    "i could not find", "i was unable to find",
    "this is uncertain", "i don't have enough information",
    "i cannot determine", "insufficient data",
    "this may not be accurate", "i'm not confident",
]


def _check_escalation_triggers(
    result: str, crew_name: str, difficulty: int,
    reflexion_exhausted: bool = False,
) -> str | None:
    """Check if the response should carry a confidence/uncertainty note (L6).

    Returns an escalation note string if any trigger fires, or None.
    Does NOT block delivery — appends transparent uncertainty labeling.
    """
    if not result:
        return None

    result_lower = result.lower()
    reasons = []

    # Check for explicit uncertainty phrases in the output
    for phrase in _UNCERTAINTY_PHRASES:
        if phrase in result_lower:
            reasons.append("response contains explicit uncertainty markers")
            break

    # Suspiciously short output for complex task
    if difficulty >= 8 and crew_name in ("research", "writing") and len(result.strip()) < 100:
        reasons.append(f"response is very short ({len(result.strip())} chars) for a complex task")

    # Reflexion loop was exhausted without satisfactory result
    if reflexion_exhausted:
        reasons.append("multiple retry attempts did not fully resolve quality concerns")

    if not reasons:
        return None

    # Build transparency note
    reason_text = "; ".join(reasons)
    return f"\n\nNote: {reason_text}. Consider verifying independently."


# ── L5: Ecological Awareness ──────────────────────────────────────────────────

def _store_ecological_report(
    crew_name: str, difficulty: int, duration_s: float
) -> None:
    """Store resource consumption footprint for ecological self-awareness (L5).

    Passive telemetry — no LLM calls, just memory storage.
    """
    from app.memory.scoped_memory import store_scoped
    text = (
        f"ECOLOGICAL: crew={crew_name}, difficulty={difficulty}, "
        f"duration={duration_s:.1f}s"
    )
    store_scoped("scope_ecology", text, {
        "type": "ecology",
        "crew": crew_name,
        "difficulty": str(difficulty),
    })
    logger.debug(f"Ecological report: {crew_name} d={difficulty} {duration_s:.1f}s")


# ── L2: World Model Prediction Tracking ──────────────────────────────────────

def _store_world_model_prediction(
    crew_name: str, difficulty: int, result: str, duration_s: float
) -> None:
    """Store prediction-vs-reality for complex tasks (L2 world model).

    Only called for difficulty >= 6 tasks. Builds causal knowledge
    about which crew/difficulty combos succeed or fail.
    """
    from app.self_awareness.world_model import store_prediction_result
    import hashlib
    task_id = f"{crew_name}_{hashlib.md5(result[:100].encode()).hexdigest()[:8]}"

    # Heuristic quality assessment (no LLM call)
    result_ok = bool(result) and len(result.strip()) > 30
    prediction = f"{crew_name} crew at difficulty {difficulty} should produce quality output"
    actual = "succeeded" if result_ok else "failed or produced low-quality output"
    lesson = (
        f"{crew_name} at difficulty {difficulty} completed in {duration_s:.1f}s"
        if result_ok
        else f"{crew_name} at difficulty {difficulty} produced insufficient output ({len(result)} chars)"
    )
    store_prediction_result(task_id, prediction, actual, lesson)
