"""architecture_adoption — proactive monitor for low-adoption
completed architecture requests.

PROGRAM §45.1 — Q7.1. Closes the §32.5 architecture-request loop:
when a subsystem has been COMPLETED for 30+ days but shows
adoption score below LOW_ADOPTION_THRESHOLD, propose a rollback CR
for operator review.

The monitor NEVER auto-applies rollback. It writes one CR per
flagged request via the standard ``change_requests.lifecycle``
gate; the operator approves or rejects via the usual flow. This
matches the Q5/Q6 anti-Goodhart pattern: signal → operator review,
never signal → auto-action.

Master switches:

  * Top-level ``architecture_requests_enabled`` — gates the entire
    arch-requests subsystem; if OFF, no monitor.
  * Monitor-level ``architecture_adoption_monitor_enabled`` —
    gates this specific monitor. Default ON per operator decision.

Dedup: the monitor records an alert-issued ledger entry per
request-id so it doesn't re-propose a rollback CR every day. Once
a request has been flagged, the next probe skips it until the
operator either approves the rollback CR (status flips out of
COMPLETED) or overrides via the per-request adoption_override
field on the ArchitectureRequest.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


NAME = "architecture_adoption"
CADENCE_SECONDS = 24 * 3600          # daily probe
MASTER_SWITCH_KEY = "architecture_adoption_monitor_enabled"


def _default_flagged_state_path() -> Path:
    """Per-request dedup state. Keyed by request_id; tracks
    when the monitor proposed a rollback so the next probe doesn't
    re-propose."""
    try:
        from app.paths import WORKSPACE_ROOT
        return Path(WORKSPACE_ROOT) / "architecture_requests" / ".adoption_flagged.json"
    except Exception:
        return Path("/app/workspace/architecture_requests/.adoption_flagged.json")


def _load_flagged() -> dict[str, str]:
    """Read the dedup state. Map request_id → flagged_at ISO timestamp."""
    path = _default_flagged_state_path()
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8")) or {}
    except (OSError, json.JSONDecodeError):
        return {}


def _save_flagged(state: dict[str, str]) -> None:
    """Atomic-write the dedup state."""
    path = _default_flagged_state_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(state, indent=2, sort_keys=True), encoding="utf-8")
        tmp.replace(path)
    except OSError:
        logger.debug("architecture_adoption: dedup state write failed")


def _propose_rollback_cr(report: Any) -> str | None:
    """File a CR proposing rollback of the scaffolded subsystem.

    The CR body explains: which subsystem, completed_at, adoption
    score, signal breakdown, and the rollback proposal. The operator
    approves or rejects via the normal CR gate.

    Returns the CR request_id on success, None on failure.
    Failure-isolated."""
    try:
        from app.change_requests.lifecycle import create_request
    except Exception:
        logger.debug("architecture_adoption: change_requests unavailable", exc_info=True)
        return None
    body = (
        f"Architecture request {report.request_id!r} "
        f"({report.package_path}) shows low adoption signal after "
        f"{report.window_days} days post-completion.\n\n"
        f"Adoption score: {report.score:.2f} "
        f"(threshold: {0.2}).\n"
        f"  - Imports referencing the package: {report.n_imports}\n"
        f"  - Idle-job audit entries:          {report.n_idle_runs}\n"
        f"  - Workspace output files:          {report.n_outputs}\n"
        f"  - Operator interactions:           {report.n_operator_interactions}\n\n"
        f"Proposing rollback of the scaffolded files. Operator should "
        f"approve if the subsystem is genuinely unused, OR reject + "
        f"override via the per-request adoption_override field if the "
        f"subsystem is valid but the scoring is wrong.\n\n"
        f"This proposal was generated by the architecture_adoption "
        f"healing monitor (PROGRAM §45.1)."
    )
    try:
        # Use the request_id as a marker path so the CR is queryable
        # but doesn't fan out an actual file rollback yet — the
        # operator-approved follow-up is the rollback action.
        marker_path = f"workspace/architecture_requests/{report.request_id}/proposed_rollback.md"
        cr = create_request(
            path=marker_path,
            content=body,
            requestor="architecture_adoption_monitor",
            reason=f"low adoption: score={report.score:.2f}",
        )
        return getattr(cr, "id", None)
    except Exception:
        logger.debug(
            "architecture_adoption: create_request failed", exc_info=True,
        )
        return None


def _notify_operator(report: Any, cr_id: str | None) -> None:
    """Best-effort Signal alert. Failure-isolated."""
    try:
        from app.notify import notify
        body = (
            f"Subsystem {report.package_path!r} (arch-request "
            f"{report.request_id}) shows zero/low adoption {report.window_days}d "
            f"after completion (score: {report.score:.2f}). "
            + (f"Rollback CR filed: {cr_id}. " if cr_id else "")
            + "See /cp/architecture-requests for detail."
        )
        notify(
            title="🏗 Low adoption: architecture request",
            body=body,
            url="/cp/architecture-requests",
            topic=f"arch_adoption_low:{report.request_id}",
            critical=False,
            arbitrate=True,
        )
    except Exception:
        logger.debug("architecture_adoption: notify failed", exc_info=True)


def run() -> dict[str, Any]:
    """One monitor probe. Failure-isolated."""
    summary: dict[str, Any] = {
        "checked": 0,
        "flagged": 0,
        "skipped_already_flagged": 0,
        "skipped_disabled": False,
    }
    # Per-monitor switch.
    try:
        from app.runtime_settings import get_architecture_adoption_monitor_enabled
        if not get_architecture_adoption_monitor_enabled():
            summary["skipped_disabled"] = True
            return summary
    except Exception:
        pass  # default ON
    # Top-level subsystem switch.
    try:
        from app.runtime_settings import get_architecture_requests_enabled
        if not get_architecture_requests_enabled():
            summary["skipped_disabled"] = True
            return summary
    except Exception:
        pass  # default ON

    try:
        from app.architecture_requests.adoption import (
            list_completed_eligible_for_measurement,
            measure,
        )
    except Exception:
        logger.debug("architecture_adoption: adoption module import failed",
                     exc_info=True)
        return summary

    flagged = _load_flagged()
    candidates = list_completed_eligible_for_measurement()
    summary["checked"] = len(candidates)

    new_flags: dict[str, str] = dict(flagged)
    now_iso = datetime.now(timezone.utc).isoformat()

    for request_id in candidates:
        if request_id in flagged:
            summary["skipped_already_flagged"] += 1
            continue
        try:
            report = measure(request_id)
        except Exception:
            logger.debug(
                "architecture_adoption: measure raised for %s",
                request_id, exc_info=True,
            )
            continue
        if report is None:
            continue
        if not report.is_low_adoption:
            continue
        # Low adoption detected.
        summary["flagged"] += 1
        cr_id = _propose_rollback_cr(report)
        _notify_operator(report, cr_id)
        new_flags[request_id] = now_iso

    if new_flags != flagged:
        _save_flagged(new_flags)
    return summary
