// IncidentsPanel — recent post-mortem incidents.
//
// Shows a list of incident summaries; clicking one expands an inline
// IncidentDetail with timeline, enabling factors, behavioral changes,
// and a Self-Improver emit indicator.
import { useState } from 'react';
import {
  useIncidentDetailQuery,
  useIncidentsQuery,
} from '../../api/epistemic';
import type {
  IncidentDetailDTO,
  IncidentSummaryDTO,
  Severity,
  TimelineEntryDTO,
} from '../../types/epistemic';

const SEVERITY_TONE: Record<Severity, string> = {
  low: 'text-[#7a8599] bg-[#11151c]',
  medium: 'text-[#fbbf24] bg-[#1f1c0e]',
  high: 'text-[#fb923c] bg-[#1f1407]',
  critical: 'text-[#f87171] bg-[#1f0e0e]',
};

export function IncidentsPanel() {
  const incidentsQuery = useIncidentsQuery(50);
  const [selected, setSelected] = useState<string | null>(null);

  return (
    <section className="rounded-lg bg-[#111820] border border-[#1e2738] p-4 space-y-3">
      <header>
        <h2 className="text-lg font-medium text-[#e2e8f0]">
          Incident reports
        </h2>
        <p className="text-xs text-[#7a8599]">
          Aviation-style post-mortems generated by{' '}
          <code>app.epistemic.postmortem.synthesize_report</code>. Each
          incident is fed to the Self-Improver loop as a learning gap.
        </p>
      </header>

      {incidentsQuery.isLoading ? (
        <ListSkeleton />
      ) : incidentsQuery.isError ? (
        <ErrorRow>{String(incidentsQuery.error)}</ErrorRow>
      ) : incidentsQuery.data && incidentsQuery.data.incidents.length > 0 ? (
        <ul className="divide-y divide-[#1e2738]">
          {incidentsQuery.data.incidents.map((inc) => (
            <IncidentRow
              key={inc.incident_id}
              incident={inc}
              expanded={selected === inc.incident_id}
              onToggle={() =>
                setSelected((cur) =>
                  cur === inc.incident_id ? null : inc.incident_id,
                )
              }
            />
          ))}
        </ul>
      ) : (
        <EmptyState />
      )}
    </section>
  );
}

function IncidentRow({
  incident,
  expanded,
  onToggle,
}: {
  incident: IncidentSummaryDTO;
  expanded: boolean;
  onToggle: () => void;
}) {
  const detailQuery = useIncidentDetailQuery(expanded ? incident.incident_id : null);
  return (
    <li className="py-3">
      <button
        onClick={onToggle}
        className="w-full text-left flex items-start gap-3 hover:bg-[#0a0e14]/50 -mx-2 px-2 rounded"
      >
        <span
          className={`px-2 py-0.5 rounded text-xs whitespace-nowrap ${SEVERITY_TONE[incident.severity]}`}
        >
          {incident.severity}
        </span>
        <div className="flex-1 min-w-0">
          <p className="text-sm text-[#e2e8f0]">
            <code className="text-[#22d3ee]">{incident.root_cause_bias_id}</code>
          </p>
          <p className="text-xs text-[#7a8599] mt-0.5">
            <code className="text-[#7a8599]">{incident.incident_id}</code>
            <span className="mx-1">·</span>
            task <code className="text-[#7a8599]">{incident.task_id}</code>
            <span className="mx-1">·</span>
            {new Date(incident.created_at).toLocaleString()}
          </p>
        </div>
        <div className="flex flex-col items-end gap-0.5 text-xs whitespace-nowrap">
          {incident.self_improver_emitted ? (
            <span className="text-[#34d399]">→ Self-Improver</span>
          ) : (
            <span className="text-[#7a8599]">queued</span>
          )}
          <span className="text-[#7a8599]">{expanded ? '▾' : '▸'}</span>
        </div>
      </button>
      {expanded && (
        <div className="mt-3 ml-8">
          {detailQuery.isLoading && <ListSkeleton />}
          {detailQuery.isError && (
            <ErrorRow>{String(detailQuery.error)}</ErrorRow>
          )}
          {detailQuery.data && <IncidentDetail detail={detailQuery.data} />}
        </div>
      )}
    </li>
  );
}

function IncidentDetail({ detail }: { detail: IncidentDetailDTO }) {
  return (
    <div className="space-y-4">
      {detail.missed_signals.length > 0 && (
        <Section title="Missed signals">
          <ul className="text-sm text-[#fb923c] space-y-1">
            {detail.missed_signals.map((s, i) => (
              <li key={i}>· {s}</li>
            ))}
          </ul>
        </Section>
      )}

      <Section title="Timeline">
        <ol className="border-l-2 border-[#1e2738] pl-4 space-y-2">
          {detail.timeline.map((e, i) => (
            <TimelineRow key={i} entry={e} />
          ))}
        </ol>
      </Section>

      {detail.enabling_factors.length > 0 && (
        <Section title="Enabling factors">
          <ul className="text-sm text-[#7a8599] space-y-1">
            {detail.enabling_factors.map((f, i) => (
              <li key={i}>
                <code className="text-[#22d3ee]">{f.bias_id}</code>{' '}
                <span className="text-xs">({f.severity})</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {detail.behavioral_changes.length > 0 && (
        <Section title="Behavioral changes proposed">
          <ul className="space-y-2">
            {detail.behavioral_changes.map((bc, i) => (
              <li
                key={i}
                className="rounded border border-[#1e2738] bg-[#0a0e14] p-2"
              >
                <div className="text-xs text-[#7a8599]">{bc.kind}</div>
                <div className="text-sm text-[#e2e8f0] mt-0.5">
                  → <code className="text-[#a78bfa]">{bc.target}</code>
                </div>
                <p className="text-xs text-[#e2e8f0] mt-1 whitespace-pre-wrap">
                  {bc.body}
                </p>
              </li>
            ))}
          </ul>
        </Section>
      )}

      <div className="text-xs text-[#7a8599] pt-2 border-t border-[#1e2738]">
        {detail.self_improver_emitted ? (
          <span className="text-[#34d399]">
            ✓ flushed to Self-Improver gap pipeline
          </span>
        ) : (
          <span className="text-[#fbbf24]">
            ⏳ persisted, awaiting Self-Improver flush
          </span>
        )}
      </div>
    </div>
  );
}

function TimelineRow({ entry }: { entry: TimelineEntryDTO }) {
  return (
    <li className="relative">
      <span className="absolute -left-[21px] top-1.5 w-2.5 h-2.5 rounded-full bg-[#60a5fa]" />
      <div className="text-xs text-[#7a8599]">
        {new Date(entry.at).toLocaleTimeString()}
        <span className="mx-1">·</span>
        {entry.kind}
        {entry.severity && (
          <>
            <span className="mx-1">·</span>
            <span className={SEVERITY_TONE[entry.severity].split(' ')[0]}>
              {entry.severity}
            </span>
          </>
        )}
      </div>
      <div className="text-sm text-[#e2e8f0]">{entry.summary}</div>
    </li>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h4 className="text-xs uppercase tracking-wide text-[#7a8599]">
        {title}
      </h4>
      <div className="mt-1">{children}</div>
    </section>
  );
}

function EmptyState() {
  return (
    <div className="rounded border border-[#1e2738] bg-[#0a0e14] p-4 text-sm text-[#7a8599]">
      No incidents recorded. Incidents are generated by{' '}
      <code>synthesize_report(task_id)</code> when at least one bias
      detector fires on a task.
    </div>
  );
}

function ListSkeleton() {
  return (
    <div className="space-y-2">
      {Array.from({ length: 3 }).map((_, i) => (
        <div
          key={i}
          className="h-12 rounded border border-[#1e2738] bg-[#0a0e14] animate-pulse"
        />
      ))}
    </div>
  );
}

function ErrorRow({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded bg-[#1a0e0e] border border-[#f87171]/40 p-3 text-sm text-[#f87171]">
      {children}
    </div>
  );
}
