#!/usr/bin/env python3
"""Generate the AndrusAI System Analysis PDF report."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)

OUTPUT = "/Users/andrus/BotArmy/crewai-team/reports/andrusai_system_analysis.pdf"

# Colors
DARK = HexColor("#1a1a2e")
ACCENT = HexColor("#e94560")
BLUE = HexColor("#0f3460")
LIGHT_GRAY = HexColor("#f5f5f5")
MED_GRAY = HexColor("#e0e0e0")
WHITE = HexColor("#ffffff")

styles = getSampleStyleSheet()

# Custom styles
styles.add(ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=28,
                          textColor=DARK, spaceAfter=6, alignment=TA_CENTER))
styles.add(ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=14,
                          textColor=BLUE, alignment=TA_CENTER, spaceAfter=20))
styles.add(ParagraphStyle("H1", parent=styles["Heading1"], fontSize=18,
                          textColor=DARK, spaceBefore=20, spaceAfter=10,
                          borderWidth=1, borderColor=ACCENT, borderPadding=4))
styles.add(ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14,
                          textColor=BLUE, spaceBefore=14, spaceAfter=6))
styles.add(ParagraphStyle("H3", parent=styles["Heading3"], fontSize=11,
                          textColor=DARK, spaceBefore=10, spaceAfter=4))
styles.add(ParagraphStyle("Body", parent=styles["Normal"], fontSize=9.5,
                          leading=13, alignment=TA_JUSTIFY, spaceAfter=6))
styles.add(ParagraphStyle("BodyBold", parent=styles["Normal"], fontSize=9.5,
                          leading=13, alignment=TA_LEFT, spaceAfter=4,
                          fontName="Helvetica-Bold"))
styles.add(ParagraphStyle("Score", parent=styles["Normal"], fontSize=36,
                          textColor=ACCENT, alignment=TA_CENTER,
                          fontName="Helvetica-Bold", spaceAfter=4))
styles.add(ParagraphStyle("ScoreLabel", parent=styles["Normal"], fontSize=10,
                          textColor=BLUE, alignment=TA_CENTER, spaceAfter=16))
styles.add(ParagraphStyle("BulletItem", parent=styles["Normal"], fontSize=9.5,
                          leading=13, leftIndent=20, bulletIndent=10,
                          spaceAfter=3))
styles.add(ParagraphStyle("SmallNote", parent=styles["Normal"], fontSize=8,
                          textColor=HexColor("#666666"), alignment=TA_CENTER))


def make_table(headers, rows, col_widths=None):
    data = [headers] + rows
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8.5),
        ("FONTSIZE", (0, 1), (-1, -1), 8.5),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("GRID", (0, 0), (-1, -1), 0.5, MED_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def build():
    doc = SimpleDocTemplate(OUTPUT, pagesize=A4,
                           topMargin=2*cm, bottomMargin=2*cm,
                           leftMargin=2*cm, rightMargin=2*cm)
    story = []
    W = doc.width

    # ── TITLE PAGE ──
    story.append(Spacer(1, 60))
    story.append(Paragraph("AndrusAI", styles["ReportTitle"]))
    story.append(Paragraph("Comprehensive System Analysis Report", styles["Subtitle"]))
    story.append(HRFlowable(width="60%", thickness=2, color=ACCENT,
                            spaceAfter=20, spaceBefore=10))
    story.append(Paragraph("8.2 / 10", styles["Score"]))
    story.append(Paragraph("Overall System Assessment", styles["ScoreLabel"]))
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "Strong architecture, good resilience, excellent self-improvement infrastructure. "
        "Main gaps: code pattern fragmentation, evolution system coordination, "
        "and idle scheduler blocking.",
        styles["Body"]))
    story.append(Spacer(1, 30))
    story.append(Paragraph("April 11, 2026", styles["SmallNote"]))
    story.append(Paragraph("Generated by Claude Code deep analysis session", styles["SmallNote"]))
    story.append(PageBreak())

    # ── EXECUTIVE SUMMARY ──
    story.append(Paragraph("Executive Summary", styles["H1"]))
    story.append(Paragraph(
        "AndrusAI is a self-improving multi-agent AI system built on CrewAI with 8 agents, "
        "7 crew types, a 17-layer consciousness architecture, 4 evolution strategies, and "
        "5 memory backends. After 4 rounds of systematic fixes, the system achieves 100% "
        "hook wiring (13/13), full sentience data persistence (36 PostgreSQL columns), and "
        "production-grade resilience (circuit breakers, native timeouts, message dedup, "
        "pool reset, forwarder reconnection).", styles["Body"]))
    story.append(Paragraph(
        "This report identifies remaining structural debt across code patterns, "
        "component interoperability, and performance. The system is architecturally "
        "ahead of all open-source agent frameworks in self-improvement and consciousness "
        "infrastructure, but trails enterprise standards in code quality hygiene.",
        styles["Body"]))

    story.append(Paragraph("System at a Glance", styles["H2"]))
    story.append(make_table(
        ["Component", "Count", "Status"],
        [
            ["Agents", "8 (researcher, coder, writer, critic, media, introspector, commander, planner)", "All active"],
            ["Crews", "7 (research, coding, writing, media, direct, retrospective, tech-radar)", "All wired"],
            ["Lifecycle Hooks", "13 across 8 hook points", "100% wired"],
            ["Evolution Strategies", "4 (Autoresearch, Island, Parallel, MAP-Elites)", "All active"],
            ["Memory Backends", "5 (ChromaDB, Mem0, pgvector, SQLite, JSON)", "All connected"],
            ["Sentience Layers", "17 (certainty, somatic, meta-cognitive, Beautiful Loop, etc.)", "Fully persisted"],
            ["Test Suites", "10 suites, 942 tests", "All passing"],
            ["Idle Scheduler Jobs", "33", "All reachable"],
        ],
        col_widths=[3.5*cm, 10*cm, 3*cm],
    ))
    story.append(PageBreak())

    # ── 1. CODE PATTERN ANALYSIS ──
    story.append(Paragraph("1. Code Pattern Analysis", styles["H1"]))

    story.append(Paragraph("1.1 Error Handling Inconsistency", styles["H2"]))
    story.append(Paragraph(
        "The codebase uses three distinct error handling patterns interchangeably "
        "within the same modules. This is the single largest code quality issue.",
        styles["Body"]))
    story.append(make_table(
        ["Pattern", "Count", "Files", "Quality"],
        [
            ["except Exception: pass", "~380", "92", "Poor - lost debug context"],
            ["except ... as e: logger.debug(...)", "~150", "60", "Adequate - debug mode only"],
            ["except ... as e: logger.error(...)", "~78", "40", "Good - production visible"],
        ],
        col_widths=[5*cm, 2*cm, 1.5*cm, 5*cm],
    ))
    story.append(Paragraph(
        "Top offenders: firebase/publish.py (22 silent swallows), orchestrator.py (17), "
        "lifecycle_hooks.py (13), evolution.py (12).",
        styles["Body"]))
    story.append(Paragraph(
        "<b>Recommendation:</b> Establish 3-tier policy: safety-critical paths use logger.error() + alert, "
        "operational paths use logger.warning(), best-effort paths (telemetry) use logger.debug(). "
        "Ban silent pass entirely.",
        styles["Body"]))

    story.append(Paragraph("1.2 File I/O Without Atomic Writes", styles["H2"]))
    story.append(Paragraph(
        "10 files write JSON/text directly via open() or Path.write_text() without "
        "atomic temp+rename. Risk: partial writes on crash corrupt state files "
        "(homeostasis.json, agent_state.json, sentience_config.json, evolution archives).",
        styles["Body"]))
    story.append(Paragraph(
        "<b>Recommendation:</b> Create a shared safe_write(path, data) utility using "
        "tempfile.NamedTemporaryFile + os.rename for all state file persistence.",
        styles["Body"]))

    story.append(Paragraph("1.3 Embedding Dimension Implicit Negotiation", styles["H2"]))
    story.append(Paragraph(
        "Two embedding backends produce different dimensions: Ollama nomic-embed-text (768-dim, "
        "Metal GPU, ~15ms) vs CPU fallback all-MiniLM-L6-v2 (384-dim, ~500ms). When Ollama "
        "is unavailable, the system silently falls back to 384-dim, triggering ChromaDB "
        "collection recreation with data loss.",
        styles["Body"]))
    story.append(Paragraph(
        "<b>Recommendation:</b> Pin embedding dimension in config. If fallback produces "
        "different dimension, refuse to store rather than silently recreate collections.",
        styles["Body"]))

    story.append(Paragraph("1.4 LLM Call Method Fragmentation", styles["H2"]))
    story.append(Paragraph(
        "4 distinct LLM call patterns: crew.kickoff(), create_specialist_llm().call(), "
        "requests.post() to Ollama, llm_factory._cached_llm(). Partly intentional "
        "(different control levels), but creates maintenance burden.",
        styles["Body"]))

    story.append(Paragraph("1.5 Datetime Timezone Inconsistency", styles["H2"]))
    story.append(Paragraph(
        "195 datetime.now() calls across 88 files. Most use timezone.utc but some create "
        "naive datetimes. No enforcement mechanism.",
        styles["Body"]))
    story.append(PageBreak())

    # ── 2. SYSTEM ARCHITECTURE ──
    story.append(Paragraph("2. System Architecture", styles["H1"]))

    story.append(Paragraph("2.1 Message Flow", styles["H2"]))
    story.append(Paragraph(
        "13 files touched per user message. Flow: Signal iPhone -> forwarder (host) -> "
        "gateway (/signal/inbound) -> Commander._route() -> _run_crew() -> CrewAI "
        "crew.kickoff() -> quality gate -> reflexion retry -> Signal chunked response.",
        styles["Body"]))
    story.append(Paragraph(
        "Well-parallelized: 6 context sources load in parallel (5s timeout each). "
        "Routing uses circuit breaker with Anthropic->OpenRouter fallback. "
        "Reflexion retries escalate model tier (budget->mid->premium).",
        styles["Body"]))

    story.append(Paragraph("2.2 Memory Architecture", styles["H2"]))
    story.append(make_table(
        ["Backend", "Purpose", "Growth", "Pruning"],
        [
            ["ChromaDB (disk)", "Skills, reflections, team memory", "Unbounded", "Dimension mismatch recreate"],
            ["Mem0 (Postgres+Neo4j)", "Cross-session facts, entity graph", "Unbounded", "None"],
            ["pgvector (Postgres)", "Agent experiences, internal states", "Unbounded", "None"],
            ["SQLite", "Conversation history", "Unbounded", "None"],
            ["JSON files", "Homeostasis, agent_state, sentience_config", "Fixed", "N/A"],
        ],
        col_widths=[3.5*cm, 4.5*cm, 2.5*cm, 3*cm],
    ))
    story.append(Paragraph(
        "<b>Data duplication:</b> Lessons learned stored in 3 places (ChromaDB reflections, "
        "belief_state, world_model). Same fact may exist in Mem0 AND world_model. "
        "Need single-writer ownership + retention policies.",
        styles["Body"]))

    story.append(Paragraph("2.3 Evolution System Coordination Gap", styles["H2"]))
    story.append(Paragraph(
        "4 evolution strategies can mutate the same workspace files concurrently. "
        "No file locking, no version tracking, no conflict detection. "
        "Risk: Island evolution mutates a prompt while Autoresearch reverts it.",
        styles["Body"]))
    story.append(Paragraph(
        "<b>Recommendation:</b> Add workspace lock manager or git-based file versioning.",
        styles["Body"]))
    story.append(PageBreak())

    # ── 3. PERFORMANCE ──
    story.append(Paragraph("3. Performance Profile", styles["H1"]))

    story.append(Paragraph("3.1 Per-Request Latency", styles["H2"]))
    story.append(make_table(
        ["Task Type", "Difficulty", "LLM Calls", "Est. Latency"],
        [
            ["Simple question", "d=1-3", "2-3", "8-15 seconds"],
            ["Standard research", "d=4-5", "3-4", "15-25 seconds"],
            ["Complex research", "d=6-7", "5-8", "25-45 seconds"],
            ["Expert + reflexion", "d=8-10", "8-12", "40-90 seconds"],
        ],
        col_widths=[4*cm, 2.5*cm, 2.5*cm, 3.5*cm],
    ))

    story.append(Paragraph("3.2 Resource Overhead Per Request", styles["H2"]))
    story.append(make_table(
        ["Resource", "Count/Size", "Latency", "Notes"],
        [
            ["Embeddings", "8-12 per request", "120-180ms (GPU)", "LRU cache 512 entries"],
            ["PostgreSQL queries", "15-18 per request", "80-250ms total", "Dominated by Mem0"],
            ["ChromaDB queries", "6-7 parallel", "50-100ms total", "Context loading"],
            ["Thread pools", "4 pools (4+N+6+8 workers)", "Contention at 5+ users", "Ollama semaphore gates"],
            ["Context tokens", "500-1250 tokens", "Pruned by difficulty", "Budget: 800-5000 chars"],
        ],
        col_widths=[3.5*cm, 3.5*cm, 3*cm, 3.5*cm],
    ))

    story.append(Paragraph("3.3 Idle Scheduler", styles["H2"]))
    story.append(Paragraph(
        "33 jobs run sequentially in a round-robin loop. Training pipeline (5-30 min) "
        "and evolution (8 min) block lightweight jobs. Full cycle: 20-50 minutes. "
        "If a user message arrives mid-evolution, the system waits for the current "
        "iteration to complete before responding.",
        styles["Body"]))
    story.append(Paragraph(
        "<b>Recommendation:</b> Parallelize lightweight jobs (feedback-aggregate, "
        "health-evaluate, version-snapshot). Move training to hourly cron. "
        "Add hard time caps on expensive jobs.",
        styles["Body"]))
    story.append(PageBreak())

    # ── 4. INTEROPERABILITY ──
    story.append(Paragraph("4. Component Interoperability", styles["H1"]))

    story.append(Paragraph("4.1 What Works Well", styles["H2"]))
    bullets = [
        "Hook system: 13/13 hooks wired across 8 execution points + CrewAI tool bridge",
        "Sentience data flow: Beautiful Loop persisted (36 columns), published to Firebase",
        "Somatic-homeostasis coupling: Bidirectional with temporal decay and modulation",
        "Context contamination defense: 20-marker filter, system_note injection, hook guard",
        "Resilience: Native timeouts, circuit breakers, backoff, dedup, pool reset, reconnection",
        "Self-improvement: 4 evolution strategies + ATLAS + cogito + RLIF with trajectory entropy",
    ]
    for b in bullets:
        story.append(Paragraph(f"<bullet>&bull;</bullet> {b}", styles["BulletItem"]))

    story.append(Paragraph("4.2 Remaining Gaps", styles["H2"]))
    story.append(make_table(
        ["Gap", "Severity", "Impact"],
        [
            ["Evolution strategies conflict on shared files", "HIGH", "Silent data loss"],
            ["No retention policy for memory backends", "MEDIUM", "Unbounded storage growth"],
            ["Silent exception swallowing (380+)", "MEDIUM", "Debugging difficulty"],
            ["No atomic file writes for state files", "MEDIUM", "Corruption risk on crash"],
            ["Embedding dimension implicit negotiation", "MEDIUM", "Silent data loss on fallback"],
            ["Idle scheduler blocking (5-30 min)", "MEDIUM", "User request delay"],
            ["Thread pool contention (multi-user)", "LOW", "Request queueing"],
            ["Conversation store no pruning", "LOW", "SQLite growth"],
        ],
        col_widths=[6*cm, 2.5*cm, 5*cm],
    ))
    story.append(PageBreak())

    # ── 5. MARKET COMPARISON ──
    story.append(Paragraph("5. Market Comparison", styles["H1"]))
    story.append(make_table(
        ["Capability", "Industry Best (2025-26)", "AndrusAI", "Rating"],
        [
            ["Self-improvement", "Darwin Godel Machine (Sakana)", "4 strategies + ATLAS + cogito + RLIF", "LEADING"],
            ["Consciousness", "Research-only (Butlin-Chalmers)", "17-layer, Beautiful Loop, probes", "PIONEERING"],
            ["Agent orchestration", "LangGraph, CrewAI, AutoGen", "CrewAI + routing + reflexion + parallel", "STRONG"],
            ["Memory systems", "Mem0, Zep, LangMem", "5-backend multi-store architecture", "COMPREHENSIVE"],
            ["Observability", "LangSmith, W&B", "PostgreSQL + Firebase + journal + audit", "GOOD"],
            ["Resilience", "Kubernetes + circuit breakers", "Native timeouts + 3 breakers + pool reset", "GOOD"],
            ["Tool safety", "Anthropic computer use", "block_dangerous + humanist via CrewAI hooks", "GOOD"],
            ["Code quality", "Enterprise CI/CD standards", "380 silent exceptions, no atomic writes", "NEEDS WORK"],
        ],
        col_widths=[3*cm, 3.8*cm, 4.5*cm, 2.2*cm],
    ))
    story.append(PageBreak())

    # ── 6. RECOMMENDATIONS ──
    story.append(Paragraph("6. Recommendations", styles["H1"]))

    tiers = [
        ("Tier 1: Code Quality", [
            "Establish error handling policy (3-tier: error/warning/debug, ban silent pass)",
            "Create safe_write() utility for atomic JSON file writes",
            "Add now_utc() datetime utility to enforce timezone awareness",
        ]),
        ("Tier 2: Data Integrity", [
            "Add workspace lock manager for evolution system coordination",
            "Pin embedding dimension in config (refuse mismatched stores)",
            "Add retention policies: 90-day ChromaDB, 1-year experiences, conversation pruning",
        ]),
        ("Tier 3: Performance", [
            "Skip vetting for d<=2 tasks (save 3-5s, 20-30% latency for simple queries)",
            "Parallelize lightweight idle scheduler jobs",
            "Move training pipeline to hourly cron (not idle loop)",
        ]),
        ("Tier 4: Architecture", [
            "Unify LLM call interface (single abstraction for all 4 call patterns)",
            "Consolidate state files (homeostasis + agent_state + sentience_config)",
            "Add collection size limits to ChromaDB with auto-pruning",
        ]),
    ]
    for tier_name, items in tiers:
        story.append(Paragraph(tier_name, styles["H2"]))
        for i, item in enumerate(items, 1):
            story.append(Paragraph(f"<bullet>{i}.</bullet> {item}", styles["BulletItem"]))

    story.append(PageBreak())

    # ── 7. TEST COVERAGE ──
    story.append(Paragraph("7. Test Coverage", styles["H1"]))
    story.append(make_table(
        ["Suite", "Tests", "Focus"],
        [
            ["test_temporal_spatial.py", "114", "Temporal awareness, spatial context, seasons"],
            ["test_emotions.py", "83", "Somatic markers, bias, dual-channel, coupling"],
            ["test_contamination.py", "44", "Context contamination, memory filtering, guards"],
            ["test_failure_recovery.py", "65", "Circuit breakers, timeouts, dedup, reconnection"],
            ["test_consciousness_full.py", "151", "7 consciousness probes, behavioral assessment"],
            ["test_self_reflection.py", "152", "Self-awareness wiring, cogito, ingestion"],
            ["test_fiction.py", "74", "Epistemic boundary, fiction metadata, safety"],
            ["test_atlas.py", "96", "Competence tracking, skill library, learning"],
            ["test_island_evolution.py", "87", "Island evolution, migration, fitness"],
            ["test_avo_operator.py", "76", "AVO operator, fuzzy dedup, code generation"],
            ["TOTAL", "942", ""],
        ],
        col_widths=[4.5*cm, 1.5*cm, 7.5*cm],
    ))

    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="40%", thickness=1, color=MED_GRAY,
                            spaceAfter=10, spaceBefore=10))
    story.append(Paragraph(
        "Report generated by Claude Code deep analysis session, April 11, 2026.",
        styles["SmallNote"]))

    doc.build(story)
    print(f"Report generated: {OUTPUT}")


if __name__ == "__main__":
    build()
