"""
Git-based workspace backup to a remote repository (e.g. GitHub).

On startup:  initialise a git repo inside /app/workspace (if absent),
             configure the remote, and pull any existing state.
On schedule: commit all changes and push — giving cloud-redundant,
             versioned backups of skills, conversation history, and
             the learning queue.

What IS backed up:  workspace/skills/, workspace/conversations.db,
                    workspace/skills/learning_queue.md
What is NOT:        workspace/memory/  (ChromaDB binary blobs — large,
                    rebuilt automatically over time)
                    workspace/output/  (transient generated artefacts)
                    workspace/audit.log* (large, operationally sensitive)

Set WORKSPACE_BACKUP_REPO in .env to enable (e.g.
  git@github.com:you/crewai-memory-backup.git
or
  https://<PAT>@github.com/you/crewai-memory-backup.git
).
Leave unset to disable — the system works fine without backups.
"""
import logging
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

WORKSPACE = Path("/app/workspace")
_GITIGNORE = """\
# Auto-generated by workspace_sync — do not edit manually
memory/
output/
audit.log*
*.pyc
__pycache__/
*.key
*.pem
"""


def _git(*args: str, check: bool = False) -> tuple[int, str]:
    """Run a git command inside WORKSPACE.  Returns (returncode, combined output)."""
    try:
        result = subprocess.run(
            ["git", "-C", str(WORKSPACE), *args],
            capture_output=True,
            text=True,
            timeout=60,
        )
        return result.returncode, (result.stdout + result.stderr).strip()
    except subprocess.TimeoutExpired:
        return 1, "git command timed out"
    except Exception as exc:
        return 1, str(exc)


def setup_workspace_repo(backup_repo: str) -> None:
    """
    Idempotent: initialise git repo in workspace, wire up the remote,
    and do an initial pull to restore any pre-existing backup.
    Called once at application startup.
    """
    if not backup_repo:
        return

    WORKSPACE.mkdir(parents=True, exist_ok=True)

    # Initialise repo if needed
    if not (WORKSPACE / ".git").exists():
        _git("init", "-b", "main")
        _git("config", "user.email", "crewai-bot@localhost")
        _git("config", "user.name", "CrewAI Workspace Bot")
        logger.info("workspace_sync: initialised new git repo in workspace")

    # Configure credential helper using GITHUB_TOKEN env var (avoids PATs in URLs)
    gh_token = os.environ.get("GITHUB_TOKEN")
    if gh_token:
        helper_path = WORKSPACE / ".git" / "git-credential-token.sh"
        helper_path.write_text(
            f"#!/bin/sh\necho username=x-access-token\necho password={gh_token}\n"
        )
        helper_path.chmod(0o755)
        _git("config", "credential.helper", str(helper_path))
        logger.info("workspace_sync: configured git credential helper from GITHUB_TOKEN")

    # Set / update remote
    rc, _ = _git("remote", "get-url", "origin")
    if rc != 0:
        _git("remote", "add", "origin", backup_repo)
    else:
        _git("remote", "set-url", "origin", backup_repo)

    # Attempt to restore from remote — failure is non-fatal (may be a fresh/empty repo)
    rc, out = _git("fetch", "origin")
    if rc == 0:
        # Verify origin/main actually exists (remote could be empty on first use)
        rc_ref, _ = _git("rev-parse", "--verify", "origin/main")
        if rc_ref == 0:
            # Hard-reset to remote state so untracked local files don't block restore
            rc2, out2 = _git("reset", "--hard", "origin/main")
            if rc2 != 0:
                logger.warning(f"workspace_sync: restore failed: {out2}")
            else:
                logger.info("workspace_sync: restored workspace state from remote")
        else:
            logger.info("workspace_sync: remote is empty, starting fresh")
    else:
        logger.info(f"workspace_sync: fetch skipped (remote may be empty): {out}")

    # Ensure .gitignore exists — either just restored from remote, or create fresh
    gi_path = WORKSPACE / ".gitignore"
    if not gi_path.exists():
        gi_path.write_text(_GITIGNORE)


def sync_workspace(backup_repo: str) -> None:
    """
    Commit any changes in workspace and push to the remote.
    Called on the configured cron schedule (default: hourly).
    Safe to call if backup_repo is empty — returns immediately.
    """
    if not backup_repo:
        return

    # Stage everything (respecting .gitignore)
    _git("add", "-A")

    # Check whether there is anything to commit
    rc, status = _git("status", "--porcelain")
    if not status.strip():
        logger.debug("workspace_sync: nothing new to commit")
        return

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rc, out = _git("commit", "-m", f"auto: workspace sync {ts}")
    if rc != 0:
        logger.error(f"workspace_sync: commit failed — {out}")
        return

    rc, out = _git("push", "-u", "origin", "main")
    if rc != 0:
        logger.error(f"workspace_sync: push failed — {out}")
    else:
        logger.info(f"workspace_sync: pushed at {ts}")
