"""
app.self_improvement.meta_agent.amendment — TIER_IMMUTABLE amendment proposer.

When policy_gap.scan_for_policy_gaps reports a recurring pattern where
an immutable rule blocks a high-success recipe, this module generates
a written amendment proposal. The proposal is:

    1. Rendered as a Markdown document with diagnosis + suggested edit
       + risk analysis + reversal plan.
    2. Routed through the existing app.proposals.create_proposal()
       pipeline so it shows up wherever the operator already reviews
       proposals (Signal digest, /cp/proposals dashboard, etc.).
    3. Saved to /app/workspace/proposals/<NNN>_amend_<...>/proposal.md
       — the file is plain UTF-8 markdown, so the operator can
       download it directly via the gateway's existing proposals API.

What the proposer EXPLICITLY does NOT do:
    - It does not edit app/auto_deployer.py.
    - It does not pre-stage code changes that would auto-apply on
      approval. The proposal asks the operator to make the edit by
      hand. This preserves the BotArmy invariant: "the modification
      mechanism itself cannot be edited by the system."

IMMUTABLE — infrastructure-level module.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from app.self_improvement.meta_agent.policy_gap import PolicyGap

logger = logging.getLogger(__name__)


def propose_immutable_amendment(gap: PolicyGap) -> Optional[int]:
    """Render and submit a TIER_IMMUTABLE amendment proposal for ``gap``.

    Returns the proposal id on success, or None if the proposal was
    skipped (duplicate, dedup window, persistence failure).

    Side-effects:
        - Writes one .md file under /app/workspace/proposals/<NNN>_amend_*
          via app.proposals.create_proposal (operator-readable; downloadable
          through the existing /cp/proposals/<id>/file/proposal.md route).
        - Logs at INFO when a proposal is created.

    The created proposal carries proposal_type="config" so the operator's
    review flow recognises it as a non-code, manual-action change.
    """
    title = _short_title(gap)
    body = render_amendment_md(gap)
    description = (
        f"TIER_IMMUTABLE amendment proposal generated by the "
        f"meta-agent layer (self_improvement.meta_agent). The "
        f"diagnosis is captured in proposal.md; operator action "
        f"is required to apply."
    )
    rationale = (
        f"Meta-agent observed {gap.affected_outcomes} outcomes for "
        f"crew '{gap.crew_name}' with smoothed success rate "
        f"{gap.success_rate_observed:.0%}. The immutable rule on "
        f"'{gap.target_filepath}' is blocking the natural augmentation "
        f"these recipes proposed."
    )
    changes_summary = _changes_summary(gap)
    risks = _risk_summary(gap)

    try:
        from app.proposals import create_proposal
    except Exception as exc:
        logger.debug(f"amendment: proposals module unavailable: {exc}")
        return None

    try:
        pid = create_proposal(
            title=title,
            description=description,
            proposal_type="config",
            files=None,                       # NO auto-applied files; operator-only
            resolution_target=f"meta_agent.policy_gap:{gap.id}",
            rationale=rationale,
            changes_summary=changes_summary,
            risks=risks,
        )
    except Exception as exc:
        logger.warning(f"amendment: create_proposal raised: {exc}")
        return None

    if pid == -1:
        logger.debug(
            f"amendment: gap '{gap.id}' skipped (duplicate or rate-limited)"
        )
        return None

    # Overwrite the autogenerated proposal.md with our richer body. The
    # proposals module sets a default rendering; the meta-agent body is
    # specifically about TIER_IMMUTABLE and includes a downloadable
    # operator playbook, so we want our text to be the primary view.
    try:
        from app.proposals import _get_proposal_dir
        pdir = _get_proposal_dir(pid)
        if pdir is not None:
            (pdir / "proposal.md").write_text(body, encoding="utf-8")
            (pdir / "amendment.md").write_text(body, encoding="utf-8")
    except Exception:
        # Non-fatal: the proposal already exists; the operator just sees
        # the default rendering instead of our richer one.
        logger.debug("amendment: rich body write failed", exc_info=True)

    logger.info(
        "amendment: proposal #%s created — gap=%s target=%s action=%s",
        pid, gap.id, gap.target_filepath, gap.suggested_action,
    )
    return pid


# ── Markdown rendering ───────────────────────────────────────────────────────

def render_amendment_md(gap: PolicyGap) -> str:
    """Render a TIER_IMMUTABLE amendment proposal as a self-contained .md.

    The file is operator-facing: it includes the diagnosis, the
    suggested concrete edit, the risks, and the reversal plan. Pure
    function — safe to call without a live proposals pipeline (used
    by tests + the /cp/ops "preview amendment" feature).
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    target = gap.target_filepath or "(unknown — operator to identify)"

    parts: list[str] = []
    parts.append(f"# TIER_IMMUTABLE amendment proposal — {gap.crew_name} crew")
    parts.append("")
    parts.append(f"_Generated by `self_improvement.meta_agent` at {now}_")
    parts.append("")
    parts.append("> **This proposal is operator-action-only.**  No code in the meta-agent layer")
    parts.append("> can edit `app/auto_deployer.py`. The system has identified a pattern that")
    parts.append("> warrants human review of an immutable rule. Apply the suggested edit by")
    parts.append("> hand if (and only if) you agree with the diagnosis below.")
    parts.append("")

    parts.append("## Diagnosis")
    parts.append("")
    parts.append(f"- **Crew**: `{gap.crew_name}`")
    parts.append(f"- **Suspected target**: `{target}`")
    parts.append(f"- **Suggested action**: `{gap.suggested_action}`")
    parts.append(f"- **Affected recipes**: {len(gap.affected_recipes)}")
    parts.append(f"- **Affected outcomes**: {gap.affected_outcomes}")
    parts.append(
        f"- **Observed success rate (smoothed)**: "
        f"{gap.success_rate_observed:.1%}"
    )
    if gap.unresolved_tool_names:
        parts.append(f"- **Unresolved tool names**: "
                     f"{', '.join(gap.unresolved_tool_names)}")
    parts.append("")
    parts.append("**Rationale**")
    parts.append("")
    parts.append(gap.rationale)
    parts.append("")

    parts.append("## Suggested edit")
    parts.append("")
    parts.append(_render_edit_block(gap))
    parts.append("")

    parts.append("## Risks")
    parts.append("")
    parts.append(_risk_summary(gap))
    parts.append("")

    parts.append("## Reversal plan")
    parts.append("")
    parts.append(_reversal_plan(gap))
    parts.append("")

    parts.append("## Affected recipes (audit trail)")
    parts.append("")
    if gap.affected_recipes:
        for rid in gap.affected_recipes[:20]:
            parts.append(f"- `{rid}`")
        if len(gap.affected_recipes) > 20:
            parts.append(f"- ...and {len(gap.affected_recipes) - 20} more")
    else:
        parts.append("_(none captured)_")
    parts.append("")

    parts.append("---")
    parts.append("_This file is the primary artifact for the proposal. "
                 "Download it from the proposals dashboard (or fetch via "
                 "the proposals API) and review before editing the "
                 "TIER_IMMUTABLE list._")
    parts.append("")
    return "\n".join(parts)


def _render_edit_block(gap: PolicyGap) -> str:
    """Render a copy-pasteable concrete edit for the operator.

    Two cases:
      - suggested_action == "demote_to_gated": move the entry from
        TIER_IMMUTABLE to TIER_GATED.
      - suggested_action == "review" or unknown target: ask operator
        to identify the right entry — we don't synthesise paths we
        can't verify.
    """
    target = gap.target_filepath
    if not target or target == "(unknown)":
        return (
            "_The meta-agent could not identify a specific TIER_IMMUTABLE entry "
            "blocking these recipes._\n\n"
            "**Operator action**: identify the immutable rule (likely an env-gated "
            "tool factory or a `TIER_IMMUTABLE` entry) and decide whether the "
            "blocking signal warrants a tier change. If unsure, leave this proposal "
            "in `pending` — the diagnosis will refresh on the next idle sweep."
        )
    if gap.suggested_action == "demote_to_gated":
        return (
            "Move this entry from `TIER_IMMUTABLE` to `TIER_GATED` in "
            "`app/auto_deployer.py`:\n\n"
            "```diff\n"
            f"-    \"{target}\",\n"
            f"+    # \"{target}\",   # demoted to TIER_GATED — see proposal\n"
            "```\n\n"
            "And add to `TIER_GATED`:\n\n"
            "```python\n"
            f"    \"{target}\",\n"
            "```\n\n"
            "After editing, run the test suite and watch the next idle sweep — "
            "the recipes affected by this gap should start succeeding via the "
            "GATED path (canary deployment + 3× eval, per CLAUDE.md)."
        )
    return (
        f"_Suggested action `{gap.suggested_action}` requires manual operator review._\n\n"
        f"Target file: `{target}`. The meta-agent cannot generate a confident concrete "
        f"edit for this action. Examine the recipes listed below to decide whether the "
        f"observed pattern warrants a rule change."
    )


def _short_title(gap: PolicyGap) -> str:
    target = gap.target_filepath or "unknown"
    leaf = target.split("/")[-1] if "/" in target else target
    return f"meta-agent: amend immutable {leaf} ({gap.crew_name})"[:80]


def _changes_summary(gap: PolicyGap) -> str:
    if gap.suggested_action == "demote_to_gated":
        return (
            f"- Move `{gap.target_filepath}` from `TIER_IMMUTABLE` to `TIER_GATED` "
            f"in `app/auto_deployer.py`.\n"
            f"- This downgrades protection from \"never auto-modify\" to \"auto-modify "
            f"only with canary + 3× eval + rollback\".\n"
            f"- Operator action only — no code changes auto-applied by approval."
        )
    return (
        f"- Review the immutable rule on `{gap.target_filepath}`.\n"
        f"- Decide whether the recipe pattern warrants a tier change.\n"
        f"- Operator action only — no code changes auto-applied by approval."
    )


def _risk_summary(gap: PolicyGap) -> str:
    return (
        "1. **Demoting an immutable rule reduces a safety boundary.** Any path moved "
        "to `TIER_GATED` becomes auto-modifiable through the canary pipeline. Verify "
        "the file has no security-core role before approving.\n"
        "2. **The meta-agent's success-rate signal can be biased.** A recipe might "
        "succeed for reasons unrelated to the blocked tool (e.g., the task didn't "
        "actually need it). Spot-check a few of the listed recipes before approving.\n"
        "3. **Reversal is hot but not free.** Re-adding the entry to `TIER_IMMUTABLE` "
        "instantly re-blocks the path, but any modifications applied while it was "
        "GATED stay in the codebase and need separate review."
    )


def _reversal_plan(gap: PolicyGap) -> str:
    return (
        "If the amendment turns out to be wrong:\n\n"
        "1. Re-add the entry to `TIER_IMMUTABLE` in `app/auto_deployer.py`. The "
        "next dispatch picks up the tightened rule immediately.\n"
        "2. Inspect any code mutations applied to the target file while it was "
        "GATED (`git log -- <path>`) and decide whether to revert.\n"
        "3. Mark this proposal `rejected` in the proposals dashboard so the "
        "meta-agent doesn't keep proposing the same change. The dedup key "
        f"(`{gap.id}`) prevents same-pattern re-proposals."
    )
