"""Stub-skeleton generator for an APPROVED architecture request.

The scaffolder takes an APPROVED ``ArchitectureRequest`` and writes
the proposed package layout to a *staging* directory under
``workspace/architecture_requests/<id>/scaffold/``. The staging
directory is operator-reviewable; nothing lands in the repo until
each file goes through the existing :mod:`app.change_requests` gate.

What gets written
-----------------

For each :class:`FileSpec` in ``req.file_layout``:

* If ``initial_stub`` is non-empty, that exact content is written.
* Otherwise, a default minimal stub is generated:
    - ``__init__.py`` files get a one-line module docstring.
    - Other ``.py`` files get a multi-line docstring containing
      the file's stated purpose plus a ``raise NotImplementedError``
      placeholder so anything importing the module before
      implementation gets a clear failure.

A summary manifest is written to
``<scaffold_dir>/MANIFEST.md`` listing intent, motivation, every
file with its purpose, integration points, env switches, and the
test plan. This is the single artefact the operator reads to decide
whether to advance the request to SCAFFOLDED.

What doesn't get written
------------------------

Nothing in the actual repo tree. Nothing in TIER_IMMUTABLE files.
Nothing inside ``app/subia/``. The validator already rejected those
proposals; the scaffolder trusts that gate but adds defence-in-depth
checks (refuses to write outside the staging dir; refuses to overwrite
files outside the scaffold_dir).
"""
from __future__ import annotations

import logging
from pathlib import Path

from app.architecture_requests.models import ArchitectureRequest, FileSpec

logger = logging.getLogger(__name__)


_DEFAULT_STAGING_ROOT = Path("/app/workspace/architecture_requests")


def staging_dir_for(request_id: str, base: Path | None = None) -> Path:
    """Return the canonical staging directory path for a request id."""
    root = base or _DEFAULT_STAGING_ROOT
    return root / request_id / "scaffold"


def _default_stub(spec: FileSpec) -> str:
    """Generate a minimal stub for files with empty ``initial_stub``."""
    if spec.path.endswith("/__init__.py") or spec.path.endswith("\\__init__.py"):
        return f'"""{spec.purpose}"""\n'
    if spec.path.endswith(".py"):
        purpose = spec.purpose.strip()
        return (
            f'"""{purpose}\n'
            f"\n"
            f"Stub generated by app.architecture_requests.scaffolder. The\n"
            f"public surface lands here in subsequent change-requests.\n"
            f'"""\n'
            f"from __future__ import annotations\n"
            f"\n"
            f"\n"
            f"raise NotImplementedError(\n"
            f'    "stub: {spec.path} not yet implemented — see the parent '
            f'architecture-request for the design intent"\n'
            f")\n"
        )
    if spec.path.endswith(".md"):
        return f"# {spec.purpose}\n\n*Stub generated by the scaffolder.*\n"
    return ""


def _render_manifest(req: ArchitectureRequest) -> str:
    lines: list[str] = [
        f"# Architecture-request manifest — `{req.id}`",
        "",
        f"- **Intent.** {req.intent}",
        f"- **Requestor.** `{req.requestor}`",
        f"- **Package path.** `{req.package_path}`",
        f"- **Status at scaffold.** `{req.status.value}`",
        f"- **Created at.** {req.created_at}",
        "",
        "## Motivation",
        "",
        req.motivation.strip(),
        "",
        "## Test plan",
        "",
        req.test_plan.strip(),
        "",
        "## File layout",
        "",
    ]
    for fs in req.file_layout:
        lines.append(f"- `{fs.path}` — {fs.purpose}")
    if not req.file_layout:
        lines.append("(empty)")
    lines.append("")

    lines.append("## Integration points")
    lines.append("")
    if req.integration_points:
        for ip in req.integration_points:
            lines.append(f"- **{ip.kind}** → `{ip.target_module}`")
            if ip.detail:
                for k, v in ip.detail.items():
                    lines.append(f"    - `{k}`: `{v}`")
    else:
        lines.append("(none)")
    lines.append("")

    lines.append("## Env switches")
    lines.append("")
    if req.env_switches:
        for name, default in req.env_switches.items():
            lines.append(f"- `{name}` (default: `{default}`)")
    else:
        lines.append("(none)")
    lines.append("")

    lines.append(
        "---",
    )
    lines.append("")
    lines.append(
        "Approving the SCAFFOLDED → IMPLEMENTING transition triggers "
        "one change-request per file in the layout above. Each child "
        "CR goes through the standard Signal 👍 / `/cp/changes` gate "
        "before landing in the repo."
    )
    lines.append("")
    return "\n".join(lines)


def scaffold(
    req: ArchitectureRequest,
    base: Path | None = None,
) -> Path:
    """Write the stub package skeleton + manifest to the staging directory.

    Returns the staging directory path. Does NOT mutate the request's
    state — caller threads the path back through
    :func:`app.architecture_requests.lifecycle.scaffold` to record
    the SCAFFOLDED transition.

    Idempotent: re-running on the same request overwrites any
    existing stubs and the manifest, but no files are deleted.
    """
    out = staging_dir_for(req.id, base=base)
    out.mkdir(parents=True, exist_ok=True)

    for spec in req.file_layout:
        # Defence-in-depth: scaffold paths are written *under the staging
        # dir*, never into the actual repo tree. We construct the
        # destination by joining the stated path under ``out``; the
        # validator already enforced that ``spec.path`` is inside
        # ``req.package_path``, so the join is a clean nested write.
        rel = spec.path
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        content = spec.initial_stub or _default_stub(spec)
        target.write_text(content)

    manifest_path = out / "MANIFEST.md"
    manifest_path.write_text(_render_manifest(req))
    logger.info(
        "architecture_requests.scaffolder: wrote %d file(s) + manifest to %s",
        len(req.file_layout), out,
    )
    return out
