#!/usr/bin/env bash
# check-env-drift.sh — verify .env.example, secrets.sh, and the AWS/GCP
# Terraform secrets.tf files reference the same set of keys.
#
# Drift between these caused Bug #6 in the GCP e2e test (2026-05-01):
# MEM0_NEO4J_PASSWORD was in .env.example + secrets.sh but missing from
# both Terraform modules, so cloud installs deployed a Neo4j pod whose
# secret reference was unresolvable. CI now runs this on every PR to
# catch it before merge.
#
# Exit codes:
#   0   no drift
#   1   drift detected (drift report on stdout, details on stderr)
#   2   one of the source files is missing
set -euo pipefail

# Resolve repo root regardless of where script is invoked from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

ENV_EXAMPLE=".env.example"
SECRETS_SH="scripts/install/secrets.sh"
AWS_TF="deploy/terraform/aws/secrets.tf"
GCP_TF="deploy/terraform/gcp/secrets.tf"

# ── Required-presence check ─────────────────────────────────────────
for f in "$ENV_EXAMPLE" "$SECRETS_SH" "$AWS_TF" "$GCP_TF"; do
    if [[ ! -r "$f" ]]; then
        echo "FATAL: cannot read $f" >&2
        exit 2
    fi
done

# ── Helpers ─────────────────────────────────────────────────────────
# Print sorted, deduplicated env var names from a source.

env_keys_from_example() {
    # Lines like  KEY=value  or  KEY=  (skip comments + blank).
    grep -oE '^[A-Z_][A-Z0-9_]*=' "$ENV_EXAMPLE" | tr -d '=' | sort -u
}

env_keys_from_secrets_sh() {
    # Three arrays + one validate_target_specific call site reference keys
    # by name. Scrape any "QUOTED_NAME" that looks like an env var.
    {
        # SECRETS_TO_GENERATE: "KEY:length"
        grep -oE '"[A-Z_][A-Z0-9_]*:[0-9]+"' "$SECRETS_SH" \
            | sed -E 's/^"([A-Z_][A-Z0-9_]*):.*/\1/'
        # REQUIRED_API_KEYS / OPTIONAL_API_KEYS array entries: "KEY"
        grep -oE '"[A-Z_][A-Z0-9_]*"' "$SECRETS_SH" \
            | tr -d '"'
        # env_get / env_set "$ENV_FILE" "KEY"  — capture KEY
        grep -oE '"\$ENV_FILE"[[:space:]]*"[A-Z_][A-Z0-9_]*"' "$SECRETS_SH" \
            | grep -oE '"[A-Z_][A-Z0-9_]*"$' | tr -d '"'
    } | sort -u
}

env_keys_from_tf() {
    local tf="$1"
    # Match HCL fields under the generated_env block. Each line looks like
    #   MEM0_POSTGRES_HOST     = google_sql_database_instance.botarmy.private_ip_address
    # We only want keys at the top of generated_env (indented 4 spaces) —
    # avoid catching nested map keys.
    awk '
        /^locals[[:space:]]*\{/ { in_locals = 1 }
        in_locals && /generated_env[[:space:]]*=[[:space:]]*\{/ { in_env = 1; next }
        in_env && /^[[:space:]]+\}/ { in_env = 0 }
        in_env && /^[[:space:]]+[A-Z_][A-Z0-9_]*[[:space:]]*=/ {
            sub(/^[[:space:]]+/, ""); sub(/[[:space:]]*=.*/, "")
            print
        }
    ' "$tf" | sort -u
}

# ── Read all four sources ───────────────────────────────────────────
KEYS_ENV="$(env_keys_from_example)"
KEYS_SH="$(env_keys_from_secrets_sh)"
KEYS_AWS="$(env_keys_from_tf "$AWS_TF")"
KEYS_GCP="$(env_keys_from_tf "$GCP_TF")"

# ── Drift checks ────────────────────────────────────────────────────
# Each pairwise check prints a heading + the diff if any. We accumulate
# errors and report them together so a single CI run shows everything.
errors=0

report_missing() {
    local title="$1" missing="$2"
    if [[ -n "$missing" ]]; then
        echo
        echo "== $title =="
        echo "$missing" | sed 's/^/    /'
        errors=$((errors + 1))
    fi
}

# 1. Every TF-generated key must be in .env.example so users see the full
#    env surface. Drift here = "I added a key to TF but forgot to document".
missing_aws_in_env="$(comm -23 <(echo "$KEYS_AWS") <(echo "$KEYS_ENV"))"
report_missing "Keys generated by AWS terraform but absent from .env.example" "$missing_aws_in_env"

missing_gcp_in_env="$(comm -23 <(echo "$KEYS_GCP") <(echo "$KEYS_ENV"))"
report_missing "Keys generated by GCP terraform but absent from .env.example" "$missing_gcp_in_env"

# 2. Every key the local installer touches (secrets.sh) must be in
#    .env.example. Drift = "I added a key to the prompts list but never
#    documented it".
missing_sh_in_env="$(comm -23 <(echo "$KEYS_SH") <(echo "$KEYS_ENV"))"
report_missing "Keys referenced by secrets.sh but absent from .env.example" "$missing_sh_in_env"

# 3. Symmetry between the two TF modules — same set of generated keys.
#    Cloud-specific values (e.g. MEM0_POSTGRES_PORT differs in shape)
#    are still the same KEY name; just values differ. Names should match.
only_in_aws="$(comm -23 <(echo "$KEYS_AWS") <(echo "$KEYS_GCP"))"
report_missing "Keys generated only on AWS (drift between cloud modules)" "$only_in_aws"

only_in_gcp="$(comm -23 <(echo "$KEYS_GCP") <(echo "$KEYS_AWS"))"
report_missing "Keys generated only on GCP (drift between cloud modules)" "$only_in_gcp"

# 4. Required user-supplied keys (REQ in secrets.sh) should exist in
#    .env.example with a placeholder value (not just be commented out).
#    We rely on (1) for this — they're in secrets.sh.

# ── Summary ─────────────────────────────────────────────────────────
echo
if [[ "$errors" -eq 0 ]]; then
    echo "✓ env spec drift check passed"
    echo "  .env.example: $(echo "$KEYS_ENV" | wc -l | tr -d ' ') keys"
    echo "  secrets.sh:   $(echo "$KEYS_SH" | wc -l | tr -d ' ') keys"
    echo "  AWS TF env:   $(echo "$KEYS_AWS" | wc -l | tr -d ' ') keys"
    echo "  GCP TF env:   $(echo "$KEYS_GCP" | wc -l | tr -d ' ') keys"
    exit 0
else
    echo
    echo "✗ env spec drift detected — $errors discrepancies."
    echo
    echo "If a key is intentionally cloud-only (e.g. DERIVED from a managed"
    echo "resource), document it with a [DERIVED] tag in .env.example and"
    echo "include a placeholder line so this check passes."
    exit 1
fi
