# Auto-generated by app/substrate/migration.py for run_id=20260517T173442Z_7917d8b6
# Productization plan WP D Phase 3.
# Manual additions (e.g. API keys, domain, monitoring) should
# go in a SEPARATE deploy/terraform/gcp/terraform.tfvars file
# and be applied via a follow-up `terraform apply`.

project_id        = "botarmy-495107"
region            = "europe-north1"
tier              = "cheapest"
enable_monitoring = false
domain            = ""
extra_env         = {}
