"""Runbooks E + F — Postgres schema-drift remediation.

Two related families:

  * **E**: ``numeric field overflow`` — a value exceeded the column's
    declared precision/scale. Fix is a column-widening migration.
    Files a *change-request* with a generated migration so the
    operator can 👍 it on Signal; auto-apply only after approval.
  * **F**: ``column "<x>" does not exist`` — query references a
    column the schema doesn't have, usually because a pending
    migration didn't run. Surfaces a Signal alert recommending
    ``alembic upgrade head`` (or the project's equivalent).

Both intentionally route through the *operator* — schema changes
without a human eyeball are too risky for unattended self-heal.
"""
from __future__ import annotations

import logging
import re
import time
from pathlib import Path
from typing import Any

from app.healing.handlers._common import (
    audit_event,
    compute_signature,
    read_state_json,
    sample_contains,
    send_signal_alert,
    write_state_json,
    file_change_request,
)
from app.healing.runbooks import RunbookResult, register_runbook

logger = logging.getLogger(__name__)

_STATE_FILE = "schema_drift.json"

# ── Runbook E — numeric field overflow ────────────────────────────────────

_E_LOGGER = "app.control_plane.db"
_E_MESSAGE = (
    "control_plane SQL error: numeric field overflow\nDETAIL:  A field "
    "with precision 10, scale 6 must round to an absolute value less "
    "than 10^4.\n"
)
_E_SIGNATURE = compute_signature(_E_LOGGER, _E_MESSAGE)

# Pattern that extracts (precision, scale) from the DETAIL line so the
# generated migration uses the correct widening.
_DETAIL_RE = re.compile(
    r"precision\s+(\d+),\s+scale\s+(\d+)", re.IGNORECASE,
)


def _propose_widening_migration(precision: int, scale: int) -> str:
    """Generate a generic migration scaffold. Operator fills in the table+col.

    We can't introspect *which* column overflowed without query context,
    so the migration is a TODO scaffold with the right type hint.
    """
    new_precision = max(precision + 5, 20)  # widen by ≥5 digits
    return f"""-- Auto-generated by self-heal runbook E (numeric_overflow_widen)
-- Reason: numeric field overflow in control_plane.* (precision={precision}, scale={scale})
-- TODO operator: fill in <SCHEMA>.<TABLE> and <COLUMN> below before applying.

ALTER TABLE control_plane.<TABLE>
  ALTER COLUMN <COLUMN> TYPE NUMERIC({new_precision}, {scale}) USING <COLUMN>::NUMERIC({new_precision}, {scale});

-- Audit:
INSERT INTO control_plane.audit (actor, action, detail) VALUES (
  'self_heal_handler',
  'schema.widen_numeric',
  jsonb_build_object('precision_old', {precision}, 'precision_new', {new_precision}, 'scale', {scale})
);
"""


def _handle_numeric_overflow(anomaly: dict[str, Any]) -> RunbookResult:
    if not sample_contains(anomaly, "numeric field overflow"):
        return RunbookResult(
            name="numeric_overflow_widen_cr", success=False,
            detail="sample mismatch", error="sample_mismatch",
        )

    sample = anomaly.get("pattern_sample") or ""
    m = _DETAIL_RE.search(sample)
    precision, scale = (10, 6)  # falls back to the observed default
    if m:
        try:
            precision, scale = int(m.group(1)), int(m.group(2))
        except (TypeError, ValueError):
            pass

    state = read_state_json(_STATE_FILE, {"numeric_overflow": {}})
    entry = state.setdefault("numeric_overflow", {}).setdefault(
        f"p{precision}s{scale}", {"count": 0, "cr_id": None, "first_seen": time.time()},
    )
    entry["count"] = int(entry.get("count", 0)) + 1
    entry["last_seen"] = time.time()

    # Already filed a CR for this (precision, scale)? Don't duplicate.
    if entry.get("cr_id"):
        write_state_json(_STATE_FILE, state)
        audit_event(
            "schema_drift_numeric_overflow_dedup",
            cr_id=entry["cr_id"], precision=precision, scale=scale,
        )
        return RunbookResult(
            name="numeric_overflow_widen_cr", success=True,
            detail=f"already proposed cr_id={entry['cr_id']}",
        )

    # Generate migration filename in alembic-style. Path is open (workspace/migrations/),
    # not TIER_IMMUTABLE.
    ts = time.strftime("%Y%m%d_%H%M%S")
    rel_path = f"migrations/{ts}_widen_numeric_p{precision}s{scale}.sql"
    new_content = _propose_widening_migration(precision, scale)

    cr_id = file_change_request(
        path=rel_path,
        new_content=new_content,
        old_content="",
        reason=(
            f"Self-heal: numeric field overflow recurring "
            f"(precision={precision}, scale={scale}; {entry['count']} hits). "
            f"Proposed widening migration; operator must fill in TABLE + COLUMN."
        ),
        requestor="self_heal_handler",
    )

    if cr_id:
        entry["cr_id"] = cr_id
        write_state_json(_STATE_FILE, state)
        return RunbookResult(
            name="numeric_overflow_widen_cr", success=True,
            detail=f"filed change-request {cr_id} for {rel_path}",
        )

    write_state_json(_STATE_FILE, state)
    # Fallback: the change-request system might be down or rejected
    # the path; emit a Signal alert as a degraded mode.
    send_signal_alert(
        f"⚠️  Self-heal: numeric overflow recurring "
        f"(precision={precision}, scale={scale}). Couldn't auto-file a CR; "
        f"see `workspace/self_heal/schema_drift.json`.",
        tag="numeric_overflow_widen_cr",
    )
    return RunbookResult(
        name="numeric_overflow_widen_cr", success=False,
        detail="CR filing failed; alerted instead", error="cr_failed",
    )


# ── Runbook F — column does not exist ─────────────────────────────────────

# Multiple variants in the wild; we register a catch-all router with a
# substring guard. Specific signatures vary because the column name is
# part of the normalized message after stripping the quoted identifier.
_F_RATE_KEY = "column_does_not_exist"
_F_COL_RE = re.compile(r'column\s+"([^"]+)"\s+does not exist', re.IGNORECASE)


def _propose_pending_migration_marker(column: str) -> str:
    """Generate a placeholder migration file the operator can use as a
    paper-trail for running ``alembic upgrade head`` — this is a real
    file artefact so the change-request system has something concrete
    to gate.
    """
    return f"""-- Auto-generated by self-heal runbook F (schema_missing_column_cr).
--
-- Detected query referencing column "{column}" that doesn't exist on
-- the live schema. Most likely cause: a pending migration hasn't been
-- applied.
--
-- OPERATOR ACTION:
--   1. Run `alembic upgrade head` (or the project's equivalent migrate
--      command) to apply any pending migrations.
--   2. Verify the column now exists:
--        SELECT column_name FROM information_schema.columns
--         WHERE column_name = '{column}';
--   3. If step 2 still shows the column missing, the application code
--      is referencing a column that was never declared — investigate
--      the call site (grep for "{column}" in app/).
--   4. Delete this file once the migration has run; it's only a marker.

-- Trail entry — provides the audit table with a record that this
-- self-heal runbook handled the incident.
INSERT INTO control_plane.audit (actor, action, detail) VALUES (
  'self_heal_handler',
  'schema.missing_column.cr_filed',
  jsonb_build_object('column', '{column}')
);
"""


def _handle_missing_column(anomaly: dict[str, Any]) -> RunbookResult:
    if not sample_contains(anomaly, "does not exist") or not sample_contains(anomaly, "column"):
        return RunbookResult(
            name="schema_missing_column_cr", success=False,
            detail="sample mismatch", error="sample_mismatch",
        )
    sample = anomaly.get("pattern_sample") or ""
    m = _F_COL_RE.search(sample)
    column = m.group(1) if m else "<unknown>"

    state = read_state_json(_STATE_FILE, {"missing_columns": {}})
    cols = state.setdefault("missing_columns", {})
    entry = cols.setdefault(column, {
        "count": 0, "first_seen": time.time(),
        "last_alert_at": 0, "cr_id": None,
    })
    entry["count"] = int(entry.get("count", 0)) + 1
    entry["last_seen"] = time.time()

    audit_event(
        "schema_missing_column",
        column=column, count=entry["count"],
        pattern_signature=anomaly.get("pattern_signature"),
    )

    # Already filed a CR for this specific column? Don't duplicate; just
    # bump the count and (optionally) re-alert on a 24 h cooldown.
    if entry.get("cr_id"):
        write_state_json(_STATE_FILE, state)
        cool = (time.time() - entry.get("last_alert_at", 0)) >= 24 * 3600
        if cool:
            entry["last_alert_at"] = time.time()
            write_state_json(_STATE_FILE, state)
            send_signal_alert(
                f"🛠 Self-heal: missing column `{column}` still firing "
                f"({entry['count']} total). CR `{entry['cr_id']}` is open; "
                f"approve in /cp/changes to land the migration marker.",
                tag="schema_missing_column_cr",
            )
        return RunbookResult(
            name="schema_missing_column_cr", success=True,
            detail=f"already proposed cr_id={entry['cr_id']} for column={column}",
        )

    # File a CR with the placeholder migration so the operator can
    # 👍-approve it in Signal and create a paper trail.
    ts = time.strftime("%Y%m%d_%H%M%S")
    rel_path = f"migrations/{ts}_missing_column_{column}.sql"
    new_content = _propose_pending_migration_marker(column)

    cr_id = file_change_request(
        path=rel_path,
        new_content=new_content,
        old_content="",
        reason=(
            f"Self-heal: query references missing column `{column}` "
            f"({entry['count']} occurrences). Likely pending migration. "
            f"Approve to record a marker file; operator must run "
            f"`alembic upgrade head` separately."
        ),
        requestor="self_heal_handler",
    )

    if cr_id:
        entry["cr_id"] = cr_id
        entry["last_alert_at"] = time.time()
        write_state_json(_STATE_FILE, state)
        return RunbookResult(
            name="schema_missing_column_cr", success=True,
            detail=f"filed CR {cr_id} for column={column}",
        )

    # Fallback: change-request system unavailable → degrade to alert.
    entry["last_alert_at"] = time.time()
    write_state_json(_STATE_FILE, state)
    send_signal_alert(
        f"⚠️  Self-heal: missing column `{column}` "
        f"({entry['count']} occurrences). Couldn't auto-file a CR; "
        f"recommend running `alembic upgrade head`. Trail in "
        f"`workspace/self_heal/schema_drift.json`.",
        tag="schema_missing_column_cr",
    )
    return RunbookResult(
        name="schema_missing_column_cr", success=False,
        detail=f"CR filing failed for column={column}; alerted instead",
        error="cr_failed",
    )


# F (schema_missing_column) is catch-all because the column name
# participates in the normalized signature. It runs through the
# multi-router in ``handlers/multi_router.py``.
handle_missing_column = _handle_missing_column


def register() -> None:
    """Only E registers a specific hash here. F runs via the multi-router."""
    register_runbook(
        "numeric_overflow_widen_cr", _E_SIGNATURE, _handle_numeric_overflow,
    )
