"""Library trial runner — turn `pending` discoveries into trial results.

PROGRAM §46.13 (Q10.1). The :mod:`library_radar.proposer` discovers
candidate libraries and stages a proposal CR with a smoke-test
coding-session spec. THIS module runs the actual smoke test inside
a coding-session sandbox and, on pass, files an *adoption CR* for
the ``requirements.txt`` edit.

Flow per pending discovery::

    pending  →  running  →  passed    →  adoption_cr_filed
                       \\─→  failed

  1. Pop a row from ``trial_state.list_pending()`` (newest first,
     capped at ``_MAX_TRIALS_PER_PASS`` per cycle so we don't
     exhaust the coding-session quota).
  2. Look up the matching :mod:`proposal_bridge` ProposalState to
     fetch the ``coding_session_spec`` (smoke test path + pytest
     command + candidate package name).
  3. Start a coding-session via the production manager singleton.
  4. Write the smoke test (a minimal ``import <pkg>`` test) into
     the session worktree.
  5. Run ``pytest`` via the sandboxed runner.
  6. On exit-0: file an *adoption CR* for ``requirements.txt`` that
     adds the package. Standard operator gate. Mark the trial
     ``adoption_cr_filed``.
  7. On non-zero or refused: mark ``failed`` with the short reason.
  8. Discard the session (it's stateless from a feature point of
     view; the trial_state ledger carries the audit trail).

Master switch: ``LIBRARY_TRIAL_RUNNER_ENABLED`` (default ON).
Cadence-checked internally — 24h between full passes. Per-pass cap
of 3 trials prevents the runner from monopolising the coding-session
quota when a backlog accumulates.

Failure-isolated end-to-end:
  * coding-session unavailable → trial stays pending, retry next pass.
  * pytest non-zero → trial marked failed, no adoption CR.
  * change_requests unavailable → trial stays passed (re-tries
    adoption CR creation next pass).
"""
from __future__ import annotations

import logging
import os
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


_RUN_CADENCE_S = 24 * 3600
_MAX_TRIALS_PER_PASS = 3
_PYTEST_TIMEOUT_S = 120
_PIP_TIMEOUT_S = 180

_STATE_FILE = "library_trial_runner.json"


def _enabled() -> bool:
    return os.getenv("LIBRARY_TRIAL_RUNNER_ENABLED", "true").lower() in (
        "true", "1", "yes", "on",
    )


def _now_ts() -> float:
    import time as _t
    return _t.time()


# ─────────────────────────────────────────────────────────────────────
#   Smoke-test rendering
# ─────────────────────────────────────────────────────────────────────


def render_smoke_test(package: str, slug: str) -> str:
    """Generate the smoke-test Python body. Conservative: import the
    package and assert it has at least one public attribute.

    The test is generated rather than coming from the LLM because we
    don't want an LLM-hallucinated API call in the test body — the
    smoke test must reflect what the package ACTUALLY exposes, not
    what the radar LLM imagined."""
    safe_pkg = package.strip().replace("-", "_")
    # Anchor the test name to the slug, not the package, so the file
    # path matches the spec regardless of which candidate was picked.
    return (
        f'"""Smoke-import test for {package} (auto-generated by\n'
        f'library_radar.trial_runner). PROGRAM §46.13."""\n'
        f"import importlib\n"
        f"\n"
        f"\n"
        f"def test_{slug[:30]}_import():\n"
        f"    mod = importlib.import_module({safe_pkg!r})\n"
        f"    # Anything importable AND surfacing at least one public\n"
        f"    # attribute is sufficient signal of a non-dead package.\n"
        f"    public = [n for n in dir(mod) if not n.startswith('_')]\n"
        f"    assert public, f'{{{safe_pkg!r}}} has no public attributes'\n"
    )


# ─────────────────────────────────────────────────────────────────────
#   Adoption CR
# ─────────────────────────────────────────────────────────────────────


def _file_adoption_cr(
    *,
    signature: str,
    package: str,
    title: str,
    trial_log_excerpt: str,
) -> str | None:
    """Build + persist the adoption CR. Returns the CR id on success."""
    try:
        from app.change_requests.lifecycle import create_request
        from app.change_requests.models import RiskClass
    except Exception:
        logger.warning(
            "trial_runner: change_requests unavailable",
            exc_info=True,
        )
        return None

    req_path = Path(os.environ.get(
        "LIBRARY_RADAR_REQUIREMENTS_PATH",
        "/app/requirements.txt",
    ))
    try:
        old_content = req_path.read_text(encoding="utf-8") if req_path.exists() else ""
    except OSError:
        old_content = ""

    # Conservative pin: add a blank-line + comment + plain pin.
    # Operator can refine in the CR review.
    addition = (
        f"\n# Q10.1 trial-canary-adopt: smoke test passed for {title[:60]}\n"
        f"# Signature: {signature}\n"
        f"{package}\n"
    )
    new_content = old_content.rstrip("\n") + ("\n" if old_content else "") + addition

    reason = (
        f"Trial-canary-adopt (PROGRAM §46.13 Q10.1): "
        f"library `{package}` passed smoke import test in a "
        f"coding-session sandbox. Filing the requirements.txt "
        f"pin for operator review.\n\n"
        f"## Trial log excerpt\n\n"
        f"```\n{trial_log_excerpt[:800]}\n```\n"
        f"\n"
        f"Originating library_radar signature: `{signature}`.\n"
    )
    try:
        cr = create_request(
            requestor="library_radar_trial",
            path="requirements.txt",
            new_content=new_content,
            old_content=old_content,
            reason=reason,
            risk_class=RiskClass.STANDARD,
        )
    except Exception:
        logger.warning(
            "trial_runner: create_request raised for %s",
            signature, exc_info=True,
        )
        return None
    return cr.id


# ─────────────────────────────────────────────────────────────────────
#   One trial
# ─────────────────────────────────────────────────────────────────────


def _run_one_trial(state, proposal) -> tuple[str, str]:
    """Run a single smoke trial. Returns (final_status, reason)
    where final_status ∈ {passed, failed, adoption_cr_filed,
    pending} and reason is a short human-readable explanation.

    ``state`` is :class:`trial_state.TrialState`.
    ``proposal`` is the :mod:`proposal_bridge` ProposalState for
    the matching signature (carries coding_session_spec).
    """
    from app.library_radar import trial_state

    spec = getattr(proposal, "coding_session_spec", None)
    if not isinstance(spec, dict):
        msg = "missing coding_session_spec on proposal"
        trial_state.mark_failed(state.signature, error=msg)
        return "failed", msg

    package = state.package_name or (state.candidates[0] if state.candidates else "")
    if not package:
        msg = "no candidate package name to test"
        trial_state.mark_failed(state.signature, error=msg)
        return "failed", msg

    # Find the smoke-test file path from spec.files (the entry with
    # action=create).
    smoke_path: str | None = None
    for entry in (spec.get("files") or []):
        if not isinstance(entry, dict):
            continue
        if entry.get("action") == "create" and "test" in (entry.get("path") or ""):
            smoke_path = entry["path"]
            break
    if not smoke_path:
        msg = "spec has no smoke-test file entry"
        trial_state.mark_failed(state.signature, error=msg)
        return "failed", msg

    # Start a coding-session
    try:
        from app.coding_session.runtime import get_manager, worktree_root
    except Exception:
        return "pending", "coding_session runtime unavailable"
    try:
        mgr = get_manager()
        session = mgr.start(
            agent_id="library_radar_trial",
            base="HEAD",
            purpose=f"Library smoke trial: {package}",
            worktree_root=worktree_root(),
        )
    except Exception as exc:  # noqa: BLE001
        logger.debug(
            "trial_runner: session start failed for %s: %s",
            state.signature, exc,
        )
        return "pending", f"session start failed: {exc}"

    trial_state.mark_running(state.signature, session_id=session.id)

    try:
        worktree = Path(session.worktree_path)
        smoke_full = worktree / smoke_path
        smoke_full.parent.mkdir(parents=True, exist_ok=True)
        smoke_full.write_text(
            render_smoke_test(package=package, slug=state.slug),
            encoding="utf-8",
        )

        # Try `pip install <pkg>` first so the smoke test has
        # something to import. Pip needs to be in the runner
        # allowlist; if not, the trial gracefully degrades to
        # "failed with reason 'pip not allowed'" without harming
        # the gateway environment.
        from app.coding_session.runner import run as sandbox_run
        pip_result = sandbox_run(
            argv=["pip", "install", "--no-cache-dir", "--quiet", package],
            cwd=str(worktree),
            timeout_s=_PIP_TIMEOUT_S,
        )
        if pip_result.refused:
            # Skip install — the package may already be present in
            # the parent env (since we're inside the gateway
            # container) — fall through to pytest and let it speak.
            logger.debug(
                "trial_runner: pip install refused (allowlist?): %s",
                pip_result.refusal_reason,
            )
        elif pip_result.exit_code != 0:
            tail = (pip_result.stderr or pip_result.stdout)[-400:]
            trial_state.mark_failed(
                state.signature,
                error=f"pip install exit={pip_result.exit_code}: {tail}",
                pytest_exit=None,
            )
            return "failed", f"pip install failed (exit={pip_result.exit_code})"

        pytest_result = sandbox_run(
            argv=["pytest", str(smoke_path), "-q", "--no-header"],
            cwd=str(worktree),
            timeout_s=_PYTEST_TIMEOUT_S,
        )
        if pytest_result.refused:
            msg = f"pytest refused: {pytest_result.refusal_reason}"
            trial_state.mark_failed(state.signature, error=msg)
            return "failed", msg

        if pytest_result.exit_code != 0:
            tail = (pytest_result.stdout or pytest_result.stderr)[-400:]
            trial_state.mark_failed(
                state.signature,
                error=f"pytest exit={pytest_result.exit_code}: {tail}",
                pytest_exit=pytest_result.exit_code,
            )
            return "failed", (
                f"pytest failed (exit={pytest_result.exit_code})"
            )

        # Pass — file the adoption CR
        trial_state.mark_passed(
            state.signature, pytest_exit=pytest_result.exit_code,
        )
        cr_id = _file_adoption_cr(
            signature=state.signature,
            package=package,
            title=getattr(proposal, "title", "") or package,
            trial_log_excerpt=(pytest_result.stdout or "")[:800],
        )
        if cr_id:
            trial_state.mark_adoption_filed(state.signature, cr_id=cr_id)
            return "adoption_cr_filed", f"adoption CR {cr_id} filed"
        # If CR creation failed we leave state as "passed" so the
        # next pass retries the adoption-CR step.
        return "passed", "passed; adoption CR creation will retry"
    finally:
        # Always free the worktree — the trial state ledger carries
        # everything we need for retrospection.
        try:
            mgr.discard(
                session.id,
                reason="library_radar_trial: smoke test complete",
            )
        except Exception:
            logger.debug(
                "trial_runner: discard failed for %s",
                session.id, exc_info=True,
            )


# ─────────────────────────────────────────────────────────────────────
#   Public entry point — idle job
# ─────────────────────────────────────────────────────────────────────


def run_one_pass() -> dict[str, Any]:
    """Walk pending trials, run up to _MAX_TRIALS_PER_PASS. Returns
    a structured result dict."""
    summary: dict[str, Any] = {
        "status": "ran",
        "passed": 0,
        "failed": 0,
        "adoption_cr_filed": 0,
        "deferred": 0,
        "considered": 0,
    }
    if not _enabled():
        summary["status"] = "skipped_disabled"
        return summary

    try:
        from app.library_radar import trial_state
        from app.proposal_bridge import store as bridge_store
    except Exception:
        summary["status"] = "subsystem_unavailable"
        return summary

    pending = trial_state.list_pending(limit=_MAX_TRIALS_PER_PASS * 2)
    summary["considered"] = len(pending)
    if not pending:
        summary["status"] = "no_pending"
        return summary

    # Resolve proposals once
    proposals_by_sig: dict[str, Any] = {}
    try:
        for p in bridge_store.list_all():
            if p.source == "library_radar":
                proposals_by_sig[p.signature] = p
    except Exception:
        logger.debug(
            "trial_runner: bridge store list_all failed", exc_info=True,
        )

    ran = 0
    for state in pending:
        if ran >= _MAX_TRIALS_PER_PASS:
            summary["deferred"] += 1
            continue
        proposal = proposals_by_sig.get(state.signature)
        if proposal is None:
            logger.debug(
                "trial_runner: no proposal for %s; deferring",
                state.signature,
            )
            summary["deferred"] += 1
            continue
        try:
            status, reason = _run_one_trial(state, proposal)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "trial_runner: trial raised for %s: %s",
                state.signature, exc, exc_info=True,
            )
            try:
                trial_state.mark_failed(
                    state.signature,
                    error=f"trial runner exception: {exc}",
                )
            except Exception:
                pass
            summary["failed"] += 1
            continue
        ran += 1
        if status == "adoption_cr_filed":
            summary["adoption_cr_filed"] += 1
        elif status == "passed":
            summary["passed"] += 1
        elif status == "failed":
            summary["failed"] += 1
        else:
            summary["deferred"] += 1
        logger.info(
            "trial_runner: %s → %s (%s)",
            state.signature, status, reason,
        )
    return summary


# ─────────────────────────────────────────────────────────────────────
#   Idle-job wrapper
# ─────────────────────────────────────────────────────────────────────


def run() -> dict[str, Any]:
    """Idle-scheduler entry point. Cadence-guarded via the canonical
    healing-handler common state helper."""
    if not _enabled():
        return {"status": "skipped_disabled"}
    try:
        from app.healing.handlers._common import (
            read_state_json, write_state_json,
        )
    except Exception:
        # Fall through to unconditional run when the cadence helper
        # is unavailable.
        return run_one_pass()
    state = read_state_json(_STATE_FILE, {"last_run_at": 0.0})
    now = _now_ts()
    if now - float(state.get("last_run_at", 0)) < _RUN_CADENCE_S:
        return {"status": "skipped_cadence"}
    state["last_run_at"] = now
    result = run_one_pass()
    try:
        write_state_json(_STATE_FILE, state)
    except Exception:
        pass
    return result
